### ISSUE TITLE
Cover todo scanning with tests

### ISSUE THREAD

**Issue by Husterknupp** [Husterknupp/jubilant-todo-tribble#17]
- [ ] todo moves line up, text doesn't change -> changed todo (consider context change?)
 - [ ] todo moves line down, text doesn't change -> changed todo (consider context change?)
 - [ ] todo stays in the same line, text changes -> new todo/changed todo (levenstein distance?)
 - [ ] todo has same text as another todo in the same file at another line -> new todo
 - [ ] todo stays the same, all together -> no change

case 1,2 (consider context change) / 3 (word difference) should be done in another issue
